//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int idConsulta { get; set; }
        public string TituloCon { get; set; }
        public string Consulta1 { get; set; }
    }
}
